#!/usr/bin/env bash

set -euf

# Infer test name from test path
function get_testname () {
    local testpath="${1%/}"
    local testdir="${testpath##*/}"
    echo "$testdir"
}

function usage () {
    echo "Helper script to repeat a test case reported here (trace-report)."
    echo
    echo "Usage:  $0 [load|save] <test-dir>"
    echo
    echo "        load  Copies the generated C code to the build directory, so"
    echo "              that it can be recompiled manually. For convenience,"
    echo "              it will also be copied to loaded.c, to allow it to be"
    echo "              compiled using \`make loaded\`."
    echo "        save  Adds the generated Spec.hs file to the regression-low"
    echo "              test suite."
    echo
}

GITROOT="$(git rev-parse --show-toplevel)"
BUILDDIR="${GITROOT}/build/trace"
REGRESSIONDIR="${GITROOT}/test/regression-low/Regression"

if ! [ $# -eq 2 ] ; then
    echo "Error: incorrect number of arguments"
    echo
    usage
    exit 2
fi

cmd="$1"
testpath="$2"

testname="$(get_testname "$testpath")"

case "$cmd" in
    load)
        mkdir -p "$BUILDDIR"
        echo cp "${testpath}/${testname}.c" "${BUILDDIR}/${testname}.c"
        cp "${testpath}/${testname}.c" "${BUILDDIR}/${testname}.c"
        echo cp "${testpath}/${testname}.c" "${BUILDDIR}/loaded.c"
        cp "${testpath}/${testname}.c" "${BUILDDIR}/loaded.c"
        ;;
    save)
        echo cp "${testpath}/${testname}Spec.hs" "${REGRESSIONDIR}/${testname}Spec.hs"
        cp "${testpath}/${testname}Spec.hs" "${REGRESSIONDIR}/${testname}Spec.hs"
        ;;
    *)
        echo "Error: command not recognized."
        echo
        usage
        exit 2
        ;;
esac
