name:                ssm
version:             0.1.0.0
github:              "githubuser/ssm"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ssm#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- language-c-quote
- BinderAnn
- prettyprinter
- QuickCheck
- text
- parser-combinators
- megaparsec
- extra
- mainland-pretty
- time
- bytestring
- template-haskell
- ghc
- syb

library:
  source-dirs: ssm

tests:
  0-trace-parser:
    main:                Spec.hs
    source-dirs:
    - test/trace-parser
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ssm
    - QuickCheck
    - hspec
  1-regression-high:
    main:                Spec.hs
    source-dirs:
    - test/lib
    - test/regression-high
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ssm
    - directory
    - process
    - text
    - QuickCheck
    - hspec
    - Diff
  2-regression-low:
    main:                Spec.hs
    source-dirs:
    - test/lib
    - test/regression-low
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ssm
    - directory
    - process
    - text
    - QuickCheck
    - hspec
    - Diff
  3-arbitrary:
    main:                Spec.hs
    source-dirs:
    - test/lib
    - test/arbitrary
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ssm
    - directory
    - process
    - text
    - QuickCheck
    - hspec
    - Diff
